'use strict';
const VERSION='v1.0.0', GAME_ID='dancing-criminal', GAME_NAME='犯人は踊る';
const NAME_KEY='boardgamePlayerName', SESSION_KEY='dancingCriminalSessionV1';
const SERVER=(window.DANCING_CRIMINAL_CONFIG?.SERVER_URL||'').replace(/\/$/,'');
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const home=$('#home'),screen=$('#screen'),nameEl=$('#name'),roomsEl=$('#rooms'),msg=$('#globalMsg');
nameEl.value=localStorage.getItem(NAME_KEY)||'';
let session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null'), poll=null;
async function api(path,opt={}){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),7000);try{const r=await fetch(SERVER+path,{...opt,headers:{'content-type':'application/json',...(opt.headers||{})},signal:ctl.signal});const text=await r.text();let d;try{d=text?JSON.parse(text):{};}catch{throw new Error('サーバー応答がJSONではありません');}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}catch(e){if(e.name==='AbortError')throw new Error('サーバー接続がタイムアウトしました');throw e;}finally{clearTimeout(t)}}
function roomCard(id){return `<article class="room" id="${id}"><h2>ROOM ${id.slice(-1)}</h2><div class="state">接続確認中…</div><div class="people">-</div><div class="actions"><button data-join="${id}" disabled>参加</button><button class="danger" data-reset="${id}" disabled>初期化</button></div></article>`}
roomsEl.innerHTML=['room1','room2','room3','room4'].map(roomCard).join('');
async function loadRooms(){try{const d=await api('/api/rooms');for(const r of d.rooms){const el=$('#'+r.id);if(!el)continue;el.querySelector('.state').textContent=`${r.statusLabel}　${r.humans+r.cpus}/8人`;el.querySelector('.people').textContent=r.names.length?r.names.join(' / '):'参加者なし';el.querySelector('[data-join]').disabled=false;el.querySelector('[data-join]').textContent=r.names.includes(nameEl.value.trim())?'再接続':'参加';el.querySelector('[data-reset]').disabled=false;}msg.textContent='';}catch(e){msg.textContent=`ROOM取得失敗：${e.message}`;document.querySelectorAll('.room').forEach(el=>{el.querySelector('.state').textContent='サーバー接続エラー';el.querySelector('.people').textContent=e.message;});}}
roomsEl.addEventListener('click',async e=>{const j=e.target.closest('[data-join]'),r=e.target.closest('[data-reset]');if(j)return join(j.dataset.join);if(r)return reset(r.dataset.reset)});
async function join(room){const name=nameEl.value.trim();if(!name)return msg.textContent='名前を入力してください。';try{const d=await api(`/api/room/${room}/join`,{method:'POST',body:JSON.stringify({name,token:session?.room===room&&session?.name===name?session.token:null})});session={room,name,token:d.token};localStorage.setItem(SESSION_KEY,JSON.stringify(session));showRoom();}catch(e){msg.textContent=e.message}}
async function reset(room){const name=nameEl.value.trim();if(!name)return msg.textContent='名前を入力してください。';if(!confirm(`ROOM ${room.slice(-1)}を初期化しますか？`))return;try{await api(`/api/room/${room}/reset`,{method:'POST',body:JSON.stringify({name})});if(session?.room===room){session=null;localStorage.removeItem(SESSION_KEY)}await loadRooms();}catch(e){msg.textContent=e.message}}
function leaveToHome(){clearInterval(poll);poll=null;screen.hidden=true;home.hidden=false;session=null;localStorage.removeItem(SESSION_KEY);loadRooms()}
async function showRoom(){home.hidden=true;screen.hidden=false;await refreshRoom();clearInterval(poll);poll=setInterval(refreshRoom,1200)}
async function refreshRoom(){if(!session)return;try{const s=await api(`/api/room/${session.room}/state?token=${encodeURIComponent(session.token)}`);render(s);}catch(e){screen.innerHTML=`<div class="panel"><h2>接続エラー</h2><p>${esc(e.message)}</p><button id="backHome">ROOM一覧へ</button></div>`;$('#backHome').onclick=leaveToHome}}
function render(s){if(s.status==='lobby')renderLobby(s);else if(s.status==='playing')renderGame(s);else renderResult(s)}
function renderLobby(s){screen.innerHTML=`<div class="panel"><div class="topline"><h2>ROOM ${s.room.slice(-1)} ロビー</h2><button class="secondary" id="leave">退出</button></div><div class="players">${s.players.map(p=>`<div class="player">${esc(p.name)}${p.cpu?' [CPU]':''}${p.host?' ★':''}</div>`).join('')}</div>${s.me.host?`<div class="settings"><label>デッキ<select id="deck"><option value="standard" ${s.settings.deck==='standard'?'selected':''}>標準</option><option value="random" ${s.settings.deck==='random'?'selected':''}>ランダム</option></select></label><label>事件名<input id="incident" value="${esc(s.settings.incident)}" maxlength="30"></label><div><button id="addCpu">CPU追加</button> <button class="secondary" id="removeCpu">CPU削除</button></div></div><p><button id="start" ${s.players.length<3?'disabled':''}>ゲーム開始</button></p>`:'<p>ホストのゲーム開始を待っています。</p>'}<p class="msg">${esc(s.notice||'')}</p></div>`;$('#leave').onclick=()=>action('leave').then(leaveToHome);if(s.me.host){$('#addCpu').onclick=()=>action('addCpu');$('#removeCpu').onclick=()=>action('removeCpu');$('#start').onclick=()=>action('start',{settings:{deck:$('#deck').value,incident:$('#incident').value}});$('#deck').onchange=()=>action('settings',{deck:$('#deck').value,incident:$('#incident').value});$('#incident').onchange=()=>action('settings',{deck:$('#deck').value,incident:$('#incident').value})}}
function renderGame(s){localStorage.setItem(NAME_KEY,session.name);const p=s.pendingView;screen.innerHTML=`<div class="board"><div class="opponents">${s.players.filter(x=>!x.me).map(x=>`<div class="player ${x.turn?'turn':''}">${esc(x.name)}${x.cpu?' [CPU]':''}<br>${x.handCount}枚 ${x.side==='criminal'?'🟥':''}</div>`).join('')}</div><div class="center"><h2>${esc(s.settings.incident||'事件発生')}</h2><strong>${esc(s.turnName||'効果処理中')}</strong><div>${esc(s.lastEvent||'')}</div>${p?pendingHtml(p):''}<details><summary>公開履歴</summary><div class="history">${s.history.map(x=>`<div>${esc(x)}</div>`).join('')}</div></details></div><div><div>あなた：${esc(s.me.name)} / ${s.me.hand.length}枚</div><div class="hand">${s.me.hand.map(c=>`<div class="card"><b>${esc(c.name)}</b><small>${esc(c.desc)}</small><button data-card="${c.id}" ${!c.playable?'disabled':''}>使用</button></div>`).join('')}</div></div></div>`;screen.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>action('play',{cardId:b.dataset.card}));bindPending(p)}
function pendingHtml(p){if(p.kind==='target')return `<div class="choices">${p.targets.map(x=>`<button data-target="${x.id}">${esc(x.name)}</button>`).join('')}</div>`;if(p.kind==='chooseOwn')return `<div><p>${esc(p.prompt)}</p><div class="choices">${p.cards.map(c=>`<button data-own="${c.id}">${esc(c.name)}</button>`).join('')}</div></div>`;if(p.kind==='chooseHidden')return `<div><p>${esc(p.prompt)}</p><div class="choices">${Array.from({length:p.count},(_,i)=>`<button data-hidden="${i}">カード${i+1}</button>`).join('')}</div></div>`;if(p.kind==='private')return `<div class="panel"><b>${esc(p.title)}</b><p>${p.lines.map(esc).join(' / ')}</p><button id="ack">確認</button></div>`;if(p.kind==='waiting')return `<div>${esc(p.text)} (${p.done}/${p.total})</div>`;return ''}
function bindPending(p){if(!p)return;screen.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>action('chooseTarget',{targetId:b.dataset.target}));screen.querySelectorAll('[data-own]').forEach(b=>b.onclick=()=>action('chooseOwn',{cardId:b.dataset.own}));screen.querySelectorAll('[data-hidden]').forEach(b=>b.onclick=()=>action('chooseHidden',{index:+b.dataset.hidden}));if($('#ack'))$('#ack').onclick=()=>action('ack')}
function renderResult(s){screen.innerHTML=`<div class="panel"><h2>リザルト</h2><h3>${s.result.winners.map(esc).join(' / ')} の勝利</h3><p>${esc(s.result.reason)}</p><h3>最終手札</h3><div class="resultHands">${s.result.hands.map(x=>`<div><b>${esc(x.name)}</b>：${x.cards.map(esc).join('、')||'なし'} / ${esc(x.side)}</div>`).join('')}</div><h3>犯人カード移動履歴</h3><div class="history">${s.result.criminalTrail.map(esc).join('<br>')}</div>${s.me.host?'<p><button id="rematch">再戦</button> <button class="secondary" id="lobby">ロビーへ</button></p>':'<p>ホストの操作を待っています。</p>'}</div>`;if(s.me.host){$('#rematch').onclick=()=>action('rematch');$('#lobby').onclick=()=>action('backLobby')}}
async function action(type,data={}){try{await api(`/api/room/${session.room}/action`,{method:'POST',body:JSON.stringify({token:session.token,type,...data})});await refreshRoom()}catch(e){alert(e.message)}}
window.addEventListener('pageshow',()=>{if(session?.room&&session?.token)showRoom();else loadRooms()});setInterval(()=>{if(!session)loadRooms()},4000);
